### ISSUE TITLE
tmx2c issue

### ISSUE THREAD

**Issue by TattooRose** [cppchriscpp/nes-starter-kit#22] opened 2020-12-18 20:33 UTC
when trying to create the test C and H files TMX2C fails with the following.
if (data[pos].gid < 0 || data[pos].gid > 256) {

I have duplicated the TMX from the overworld tmx only difference I can see is my map is 128 wide by 12 high.

I am very new to programming a NES and even more so on using lynx in cygwin so any help would be appreicated.

thanks
Victor

**Comment by cppchriscpp** [comment] 2020-12-18 22:15
Hello! 

First, thank you for trying this project! I'm really excited to see someone using it. It is relatively new, so there are things I may need to improve. Please continue mentioning them, so I can help.


Unfortunately, right now both tmx2c and the NES game engine are hard-coded to expect a 128x96 map. The error you get from tmx2c is very unclear, and is something I could improve. I had honestly never tried resizing the map before.

To get something working, the easiest option is to use a 128 wide by 96 tall map, and fill most of it with blank tiles. A second option is to put multiple 128 wide by 12 tall maps on the same screen+tmx file, like this: 

![map preview](https://user-images.githubusercontent.com/750475/102664822-9bfae680-4151-11eb-8ea0-089975d48328.png)

Will this work for what you are trying to do? 

Cheers,
Chris

**Comment by TattooRose** [comment] 2020-12-18 22:59
Hi Chris,

 

The first solution will work for now, so I will go that root. As I get more knowledgeable on the tmx3c script I will look into it further. I come from a windows Microsoft background and have been programming for over 35 years. As I learn java script and the node js framework better I can take a look.

 

I can’t thank you enough for the quick response to this issue.

 

Thanks,

Victor

**Comment by cppchriscpp** [comment] 2020-12-19 01:21
Glad to help! Please don't be afraid to ask more questions. When you come back to it I can also point you to the general areas of code you would need to update.

I am going to add a note to the guide in the "Changing the World" section, to help people in the future who might have this same problem.

Otherwise, it sounds like the issue is solved, so I am going to close this ticket. If you have further questions, feel free to open a new issue. (Or commenting here again is okay too)

Thank you!
Chris

**Comment by TattooRose** [comment] 2020-12-19 18:15
Hi Chris,

 

Here is a little more info on the issue. I did as you suggested and expanded my map to the size of the overworld map. The map contained a tile, sprite, and room layer. I places a border for the rooms which came out to be 8 rooms per row. My width was 128 and my height was 96. Only the first room had a playable scene.

 

When I used tmx2c the same problem occurred. The error was the data[pos].gid was undefined. The value of pos was zero so this happened trying to process room (0:0).

 

I then went and on the tile layer and filled all empty space on the map with a tile. Ran the same process and all worked.

 

I am thinking that the app needs all unused areas to be filled with a tile.

 

Hope this helps.

 

Victor

**Comment by cppchriscpp** [comment] 2020-12-19 21:26
Hi again,

Yes, that is also true! I think you would get a similar error in either of those cases. 

I'm glad you were able to figure it out. 

Cheers,
Chris

**Comment by cppchriscpp** [comment] 2020-12-19 21:36
**Quick update**: I just put in a quick change to the tmx2c script if you use the nodejs versions directly, [here](https://github.com/cppchriscpp/nes-starter-kit/commit/1c084516b5a737e45dfa5e570835928760c5a639). 

I didn't rebuild the binary versions of the tools for this change, but next time I do so, it should start to handle this case better. Thanks for pointing this out!

**Comment by TattooRose** [comment] 2020-12-20 21:57
Hi,

 

The last change did work except with { gid : 1} it picks tile 0 from the tile set. You may want to note that in the docs and say tile sets should have a empty 0 tile. I tested it by changing the number to 6 and that translated to the overworld tile 5 which was blank.  Or you could take an additional argument like BlankTile and pass it in then if the user sets it use that otherwise default to one.

 

Just a suggestion.

 

Thanks again for your help,

Victor

**Comment by TattooRose** [comment] 2020-12-20 22:08
Hi again,

 

Here is my version of the script. Should have sent it over in the previous mail.

 

Victor

**Comment by cppchriscpp** [comment] 2020-12-20 23:31
Ah good catch! I'll get something documented around that now. 

I think I'm going to avoid adding a custom argument, though I appreciate the idea. You gave a good example of how to do it too, so thank you for that!

The goal I have with the pieces of this project are to give users something to hack to meet their own needs. (Like you're doing with your version of the script!) Features like that add more code for the user to understand before they can get hacking. If I thought the feature would be highly requested, I would do it, but I think keeping the script simple better meets the goals of the project. 

Thank you!

**Comment by cppchriscpp** [comment] 2021-03-26 00:50
It's been a few months, so I'm going to close this issue to keep the issue tracker clean. I'm always open to reopening this for more discussion as needed, though. Thanks for checking out the project!

(ps: I did add that documentation in 05b965602a97276130ef551ed702753990350a11 - forgot to update here when I did it.

**Closed by cppchriscpp** 2021-03-26 00:50 UTC

**Comment by unkn0wncvm1** [comment] 2022-09-29 21:03
Note: **DO NOT USE THE NPM VERSION USE THE ONE THAT COMES WITH TOOLS ZIP**
